name: Build Docker

on:
  push:
    branches:
      - main
  # permit excute this workflow by manually
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qt5126-arm-dev:latest
            ghcr.io/${{ github.repository_owner }}/qt5126-arm-dev:5.12.6
